version: '3.7'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://guane_admin:guane_admin@db/adoptions
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=guane_admin
      - POSTGRES_PASSWORD=guane_admin
      - POSTGRES_DB=adoptions

volumes:
  postgres_data: